# keys for switching panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Splitting panes.
bind - split-window -v
bind | split-window -h

# shift-movement keys will resize panes
bind J resize-pane -D 5
bind K resize-pane -U 5
bind H resize-pane -L 5
bind L resize-pane -R 5

#+---------+
#+ Options +
#+---------+
set -g status-interval 5
set -g status on

#+--------+
#+ Status +
#+--------+
#+--- Layout ---+
set -g status-justify left

#+--- Colors ---+
set -g status-bg black
set -g status-fg white
set -g status-attr none

#+-------+
#+ Panes +
#+-------+
set -g pane-border-bg black
set -g pane-border-fg black
set -g pane-active-border-bg black
set -g pane-active-border-fg brightblack
set -g display-panes-colour black
set -g display-panes-active-colour brightblack

#+------------+
#+ Clock Mode +
#+------------+
setw -g clock-mode-colour cyan

#+----------+
#+ Messages +
#+---------+
set -g message-fg cyan
set -g message-bg brightblack
set -g message-command-fg cyan
set -g message-command-bg brightblack

#+----------------+
#+ Plugin Support +
#+----------------+
#+--- tmux-prefix-highlight ---+
set -g @prefix_highlight_output_prefix "#[fg=brightcyan]#[bg=#3B4252]#[nobold]#[noitalics]#[nounderscore]#[bg=brightcyan]#[fg=#3B4252]"
set -g @prefix_highlight_output_suffix ""
set -g @prefix_highlight_copy_mode_attr "fg=brightcyan,bg=#3B4252,bold"

#+--------+
#+ Status +
#+--------+
#+--- Layout ---+
set -g status-justify left

#+--- Colors ---+
set -g status-bg "#3B4252"
set -g status-fg white
set -g status-attr none

# Bars and windows
set -g status-left "#[fg=black,bg=blue,nobold] #S #[fg=blue,bg=#3B4252,nobold,noitalics,nounderscore]"
set -g window-status-format "#[fg=#3B4252,bg=brightblack,nobold,noitalics,nounderscore] #[fg=black,bg=brightblack]#I #[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=black,bg=brightblack]#W #F #[fg=brightblack,bg=#3B4252,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=#3B4252,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #F #[fg=cyan,bg=#3B4252,nobold,noitalics,nounderscore]"
set -g window-status-separator ""
set -g status-right-length 100
set -g status-right "#{prefix_highlight}#[fg=blue,bg=#3B4252,nobold,noitalics,nounderscore]#[fg=black,bg=blue] %H:%M "


# =============================
# Plugins: KEEP THIS AT THE END
# =============================

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-pain-control' # better control of panes

set -g @plugin 'tmux-plugins/tmux-cpu' # shows cpu status in status bar
set -g @plugin 'tmux-plugins/tmux-battery' # shows battery stats in status bar
set -g @plugin 'tmux-plugins/tmux-online-status' # shows battery stats in status bar
set -g @plugin 'tmux-plugins/tmux-resurrect' # persists sessions between shutdowns/restarts

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
