# Taps
tap 'go-task/tap'
tap 'homebrew/cask'
tap 'danielfrg/homebrew-formulas'
tap 'homebrew/cask-fonts'

# Tools
brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'atuin'
brew 'bash'
brew 'bat'
brew 'bottom'
brew 'cloudflared'
brew 'curl'
brew 'diff-so-fancy'
brew 'duf'
brew 'entr'
brew 'exa'
brew 'fd'
brew 'fileicon'
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'gh'
brew 'gnupg'
brew 'gnupg2'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'go-task/tap/go-task'
brew 'grep'
brew 'httpie'
brew 'jq'
brew 'm-cli'
brew 'openssl'
brew 'pinentry-mac'
brew 'prettyping'
brew 'protobuf'
brew 'ripgrep'
brew 'reattach-to-user-namespace'
brew 'rsync'
brew 'starship'
brew 'stow'
brew 'telnet'
brew 'terraform'
brew 'the_silver_searcher'
brew 'tldr'
brew 'tmux'
brew 'trash'
brew 'unp'
brew 'viddy'
brew 'watch'
brew 'wget'
brew 'zsh'
brew 'youtube-dl'

# Python
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'hatch'

# JS
brew 'node'
brew 'yarn'

# Go
brew 'go'

# Ruby
brew 'ruby'
brew 'ruby-build'
brew 'rbenv'

# docker and k8s
# brew 'dive'
brew 'kubectl'
brew 'kubectx'
brew 'knative/client/kn'
# brew 'kube-ps1'
brew 'helm'
# brew 'draft'
# brew 'kustomize'
# brew 'kubefwd'

# Others
brew 'ansible'
# brew 'selenium-server'

###################
# Casks
###################

# cask 'chromedriver'
cask 'alacritty'
cask 'bartender'
cask 'cleanshot'
cask 'discord'
cask 'docker'
cask 'eloston-chromium'
cask 'font-jetbrains-mono-nerd-font'
# cask 'google-chrome'
cask 'google-drive'
# cask 'gpg-suite'
cask 'httpie'
cask 'karabiner-elements'
cask 'keka'
cask 'keyboard-maestro7'
cask 'homebrew/cask-drivers/logitech-options'
cask 'maccy'
cask 'monitorcontrol'
cask 'obs'
cask 'obsidian'
cask 'tableplus'
cask 'raycast'
# cask 'rectangle-pro'
# cask 'tor-browser'
cask 'visual-studio-code'
cask 'vlc'
