brew 'coreutils'
brew 'moreutils'
brew 'findutils'
# brew 'atuin'
brew 'ansible'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'bottom'
brew 'cloudflared'
brew 'curl'
brew 'diff-so-fancy'
brew 'duf'
brew 'entr'
brew 'eza'
brew 'fd'
brew 'fileicon'
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'gh'
brew 'gpg2'
brew 'gnupg'
brew 'gnu-sed'
brew 'gnu-tar'
tap 'go-task/tap'
brew 'go-task/tap/go-task'
tap 'yqrashawn/goku'
brew 'yqrashawn/goku/goku'
brew 'grep'
brew 'httpie'
brew 'jq'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'lazygit'
brew 'libpq'
brew 'm-cli'
brew 'neofetch'
brew 'neovim'
brew 'openssl'
brew 'pinentry-mac'
brew 'prettyping'
brew 'protobuf'
brew 'ripgrep'
brew 'reattach-to-user-namespace'
brew 'rsync'
brew 'stow'
brew 'telnet'
brew 'terraform'
brew 'the_silver_searcher'
brew 'tldr'
brew 'tmux'
brew 'trash'
brew 'unp'
brew 'viddy'
brew 'watch'
brew 'wget'
brew 'zsh'
brew 'yazi'
brew 'youtube-dl'
brew 'zoxide'

tap 'nikitabobko/tap'
brew 'nikitabobko/tap/aerospace'

# tap 'koekeishiya/formulae'
# brew 'koekeishiya/formulae/yabai'
# brew 'koekeishiya/formulae/skhd'

# Python
# brew 'pyenv'
# brew 'pyenv-virtualenv'
# brew 'hatch'

# JS
brew 'node'
brew 'yarn'

# Go
brew 'go'

# docker and k8s
# brew 'dive'
brew 'kubectl'
brew 'kubectx'
brew 'helm'
# brew 'kubefwd'

# Others
brew 'ansible'
# brew 'selenium-server'

###################
# Casks
###################

# cask 'alacritty'
cask 'audacity'
cask 'bartender'
cask 'blackhole-2ch'
cask 'cleanshot'
cask 'discord'
cask 'docker'
cask 'eloston-chromium'
cask 'fliqlo'
# cask 'google-chrome'
# cask 'chromedriver'
cask 'google-drive'
cask 'gpg-suite'
cask 'httpie'
cask 'iina'
cask 'karabiner-elements'
cask 'keka'
tap 'danielfrg/homebrew-formulas'
cask 'danielfrg/homebrew-formulas/keyboard-maestro7'
cask 'logi-options-plus'
cask 'maccy'
cask 'monitorcontrol'
cask 'obs'
cask 'tableplus'
cask 'raycast'
# cask 'tor-browser'
cask 'visual-studio-code'
cask 'vb-cable'
cask 'wezterm'
cask 'zed'

# Fonts
tap 'homebrew/cask-fonts'
cask 'fontbase'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-fira-code-nerd-font'
cask 'font-cascadia-code'
cask 'font-monaspace'
