brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'gnu-sed', args: ['with-default-names']

brew 'wget'
brew 'curl', args: ['with-openssl']
brew 'httpie'
brew 'zsh'
brew 'git'
brew 'tmux'
brew 'fzf'
brew 'unp'
brew 'gnupg'
brew 'sshrc'
brew 'trash'
brew 'thefuck'
brew 'watch'
brew 'tldr'
brew 'mobile-shell'
brew 'terraform'
brew 'go'
brew 'node'
brew 'yarn'
brew 'bazel'

brew 'kubectx'
brew 'draft'

tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'caskroom/cask/brew-cask'
cask 'alfred'
cask '1password'
cask 'vlc'
cask 'google-chrome'
cask 'google-drive'
cask 'firefox'
cask 'keyboard-maestro'
cask 'clipmenu'
cask 'keka'
cask 'spotify'
cask 'silverlight'
cask 'smoothmouse'

cask 'atom'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'iterm2'
cask 'java'
cask 'vagrant'
cask 'virtualbox'
cask 'insomnia'
cask 'google-cloud-sdk'
cask 'slack'
cask 'xquartz'
cask 'ngrok'
cask 'licecap'
