version: "3"

env:
  TAG: base

tasks:
  ansible:
    dir: ansible
    cmds:
      - ansible-playbook local.yml

  ansible:tag:
    dir: ansible
    cmds:
      - ansible-playbook local.yml --tags "{{.TAG}}"

  fonts:
    cmds:
      - bash install-fonts.sh

  link:
    cmds:
      - stow -t $HOME base
      - stow -t $HOME zsh
      - stow -t $HOME python
      - stow -t $HOME nvim
      - stow -t $HOME bin

  gpg:
    cmds:
      - gpg --list-keys
      - stow -t $HOME gpg
      - echo "Manually run 'gpg --import <file>' for the public and private keys"
