version: "3"

env:
  TAG: base
  dir: nvim

tasks:
  ansible:
    cmds:
      - task: ansible:laptop

  ansible:laptop:
    dir: ansible
    cmds:
      - ansible-playbook local.yml --tags "laptop"

  ansible:homelab:
    dir: ansible
    cmds:
      - ansible-playbook remote.yml --limit homelab

  ansible:rpi:
    dir: ansible
    cmds:
      - ansible-playbook remote.yml --limit rpi # --ask-become-pass

  ansible:tag:
    dir: ansible
    cmds:
      - ansible-playbook local.yml --tags "{{.TAG}}"

  fonts:
    cmds:
      - bash install-fonts.sh

  link:
    cmds:
      - stow -t $HOME base
      - stow -t $HOME bin
      - stow -t $HOME js
      - stow -t $HOME nvim
      - stow -t $HOME python
      - stow -t $HOME zsh

  unstow:
    cmds:
      - stow -t $HOME -D nvim

  gpg:
    cmds:
      - gpg --list-keys
      - stow -t $HOME gpg
      - echo "Manually run 'gpg --import <file>' for the public and private keys"
