enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[mode.main.binding]
cmd-alt-ctrl-shift-h = 'focus left'
cmd-alt-ctrl-shift-j = 'focus down'
cmd-alt-ctrl-shift-k = 'focus up'
cmd-alt-ctrl-shift-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# alt-h = 'split horizontal'
# alt-v = 'split vertical'

cmd-alt-ctrl-shift-f = 'fullscreen'
alt-f = 'fullscreen'

# alt-s = 'layout v_accordion' # 'layout stacking' in i3
# alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-s = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

cmd-alt-ctrl-shift-1 = 'workspace 1'
cmd-alt-ctrl-shift-2 = 'workspace 2'
cmd-alt-ctrl-shift-3 = 'workspace 3'
cmd-alt-ctrl-shift-4 = 'workspace 4'
cmd-alt-ctrl-shift-5 = 'workspace 5'
cmd-alt-ctrl-shift-6 = 'workspace 6'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

alt-enter = 'exec-and-forget open -n /Applications/WezTerm.app'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

# Get App ID: osascript -e 'id of app "Wezterm"'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.culturedcode.ThingsMac'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.1password.1password'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.cisco.anyconnect.gui'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
check-further-callbacks = true
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
check-further-callbacks = true
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
check-further-callbacks = true
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
check-further-callbacks = true
run = ['move-node-to-workspace 5']
