apm install language-docker
apt install language-cython
apt install language-jenkins
apm install atom-jinja2
apm install language-terraform
apm install language-powershell
apm install atom-language-r
apm install linter
apm install linter-ui-default
apm install linter-sass-lint
apm install emmet
apm install vim-mode
apm install atom-beautify
apm install highlight-selected
apm install tabs-to-spaces
apm install auto-detect-indentation
apm install sass-autocompile
