apm install language-docker
apt install language-cython
apt install language-jenkins
apm install atom-jinja2
apm install vim-mode
apm install emmet
apm install highlight-selected
apm install atom-beautify
apm install tabs-to-spaces
apm install auto-detect-indentation
apm install linter
apm install linter-ui-default
