- name: install kernel modules and ubuntu-drivers
  become: true
  ansible.builtin.package:
    name: ubuntu-drivers-common
    state: present
    update_cache: true
  with_items:
    - linux-modules-nvidia-535-generic
    # linux-modules-nvidia-535-$(uname -r)
    - linux-modules-nvidia-535-6.8.0-36-generic
    - nvidia-cuda-toolkit

- name: check ubuntu-drivers
  become: true
  command:
    cmd: ubuntu-drivers --help
  register: ubuntu_drivers_command

- name: install nvidia driver
  become: true
  when:
    - ubuntu_drivers_command.rc == 0
  command:
    cmd: "ubuntu-drivers install --gpgpu"

- name: install nvidia utils
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nvidia-utils-535-server
    - nvidia-cuda-toolkit
