- name: Include Ubuntu tasks
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Include Arch Linux tasks
  include_tasks: arch.yml
  when: ansible_distribution == 'Archlinux'
