"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
${custom.python_version}\
${custom.py_venv}\
${custom.rbenv_gemset}\
$kubernetes\
$line_break\
$character
"""

right_format = """$time"""

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 150

[character]
# success_symbol = "[➜](bold green)"
success_symbol = "[❯](bold green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[username]
style_user = 'yellow'
show_always = true

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'

[directory]
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "white"

[git_status]
style = "white"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'
style = "yellow"

[time]
# format = '\[[$time]($style)\]'
format = '[$time]($style)'
style = 'dimmed yellow'

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[golang]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[custom.foo]
command = 'echo foo'

[custom.python_version]
command = 'cat .python-version'
detect_files = ['.python-version']
symbol = "  "
style = 'bold green'

[custom.py_venv]
command = "echo $VIRTUAL_ENV | awk -F/ '{ print $NF }'"
when = ''' test "$VIRTUAL_ENV" '''
format = '\[[$output]($style)\]'
style = 'bold green'

[custom.rbenv_gemset]
command = 'cat .rbenv-gemsets'
detect_files = ['.rbenv-gemsets']
symbol = '🔺 '
style = 'bold red'

#####

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
disabled = true
symbol = "  "

[bun]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[c]
format = '\[[$symbol($version(-$name))]($style)\]'
disabled = true

[cmake]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[cobol]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[conda]
format = '\[[$symbol$environment]($style)\]'
disabled = true
symbol = " "

[crystal]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[daml]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[dart]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[deno]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[docker_context]
format = '\[[$symbol$context]($style)\]'
disabled = true

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'
disabled = true

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
disabled = true

[elm]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[erlang]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
disabled = true
symbol = "  "

[haskell]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[helm]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
disabled = true

[java]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[julia]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[kotlin]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[lua]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
disabled = true

[meson]
format = '\[[$symbol$project]($style)\]'
disabled = true

[nim]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'
disabled = true

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
disabled = true

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'
disabled = true

[package]
format = '\[[$symbol$version]($style)\]'
disabled = true

[perl]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[php]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[pulumi]
format = '\[[$symbol$stack]($style)\]'
disabled = true

[purescript]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'
disabled = true

[red]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[ruby]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[rust]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[scala]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[spack]
format = '\[[$symbol$environment]($style)\]'
disabled = true

[sudo]
format = '\[[as $symbol]\]'

[swift]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[terraform]
disabled = true

[vagrant]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[vlang]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[zig]
format = '\[[$symbol($version)]($style)\]'
disabled = true
