---

- ansible.builtin.include_tasks: packages.yml
  tags:
    - always

- ansible.builtin.include_tasks: base.yml
  tags:
    - always

- ansible.builtin.include_tasks: dotfiles.yml
  tags:
    - always
