---

- name: Install deps (apt-update)
  become: true
  ansible.builtin.apt:
    update_cache: yes
  ignore_errors: true

- name: Install deps (apt)
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    # update_cache: yes
  with_items:
    - exa
    - fzf
    - git
    - neovim
    - net-tools
    - snapd
    - stow
    - zsh
  ignore_errors: true

- name: Install dotfiles deps (snap classic)
  become: true
  community.general.snap:
    name:
      - task
    classic: true

- name: Install dotfiles deps (snap edge)
  become: true
  community.general.snap:
    name:
      - starship
    channel: latest/edge
