---
- name: check conda
  stat: path=/{{ ansible_env.HOME }}/conda
  register: conda

- name: download miniforge
  ansible.builtin.get_url:
    url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
    dest: "/tmp/conda.sh"
  when: not conda.stat.exists

- name: install conda
  command: "bash /tmp/conda.sh -p {{ ansible_env.HOME }}/conda -b"
  when: not conda.stat.exists

- name: remove installer
  ansible.builtin.file:
    path: "/tmp/conda.sh"
    state: absent
