---
- name: Create directory for GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download and add GPG key
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    dest: /tmp/gierens.asc
  register: gpg_download

- name: Check if the key file exists
  stat:
    path: /etc/apt/keyrings/gierens.gpg
  register: key_file_check

- name: Add key to keyrings
  become: true
  ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/gierens.gpg /tmp/gierens.asc
  when: not key_file_check.stat.exists

- name: Add repository to sources.list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main
    filename: gierens

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install eza
  become: true
  ansible.builtin.apt:
    name: eza
    state: present
