---
- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - git
    - git-delta
    - eza
    - fzf
    - htop
    - just
    - less
    - lazygit
    - neovim
    - openconnect
    - unzip
    - stow
    - tailscale
    - yazi
    - zsh

- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:danielfrg/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    recursive: yes
    update: yes
  tags:
    - repo

- name: Stow files
  ansible.builtin.command: just stow
  args:
    chdir: /home/{{ setup_user }}/.dotfiles

- name: Change shell to zsh
  become: true
  user:
    name: "{{ setup_user }}"
    shell: /usr/bin/zsh
