---
- name: Install deps
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - git
    - git-delta
    - eza
    - fzf
    - htop
    - less
    - neovim
    - nodejs
    - npm
    - openconnect
    - stow
    - go-task
    - zsh

- name: Ensure ~/code directory exists
  file:
    dest: "{{ ansible_env.HOME }}/code"
    state: directory

- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:danielfrg/dotfiles.git
    dest: "{{ ansible_env.HOME }}/code/dotfiles"
    recursive: yes
    update: yes
  tags:
    - repo

- name: Stow files
  ansible.builtin.command: go-task link
  args:
    chdir: /home/{{ setup_user }}/code/dotfiles

- name: Remove .tmux.conf
  file:
    path: /home/{{ setup_user }}/.tmux.conf
    state: absent

- name: Change shell to zsh
  become: true
  user:
    name: "{{ setup_user }}"
    shell: /usr/bin/zsh
