- hosts: localhost
  connection: local

  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"

  roles:
    - role: common
      tags: ["always", "common"]

    - role: laptop
      tags: ["never", "laptop"]

    - role: workstation
      tags: ["never", "workstation"]
