- hosts: nvidia

  vars:
    setup_user: danrodriguez
    docker_users:
      - danrodriguez

  roles:
    - role: dotfiles
      tags: [dotfiles]

    - role: nvidia-drivers
      tags: [gpu]

    - role: conda
      tags: [conda]

    - role: geerlingguy.docker
      become: true
      tags: [docker]
