- hosts: nvidia

  vars:
    setup_user: danielfrg
    docker_users:
      - danielfrg

  roles:
    - role: dotfiles
      tags: [dotfiles]

    - role: nvidia-drivers
      tags: [gpu]

    - role: dev
      tags: [dev]

    # - role: geerlingguy.docker
    #   become: true
    #   tags: [docker]
